{{- if and .Values.persistenceVolume.enable -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistenceVolume.persistentVolumeClaim }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "aplic.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistenceVolume.storageClass }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistenceVolume.storageSize }}
{{- end }}
