apiVersion: v1
kind: Service
metadata:
  name: {{ include "aplic.fullname" . }}
  labels:
    app: {{ include "aplic.name" . }}
    chart: {{ include "aplic.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "aplic.name" . }}
    release: {{ .Release.Name }}
{{- if .Values.service.ports }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
{{- end -}}
