{{- if and .Values.ingressExterno.enable -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "aplic.fullname" . }}-externo
  annotations:
    kubernetes.io/ingress.class: nginx-externo
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  rules:
  - host: {{ .Values.ingressExterno.hostname | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ template "aplic.fullname" . }}
          servicePort: {{ .Values.ingressExterno.servicePort }}
{{- if .Values.ingressExterno.tls }}
  tls:
{{ toYaml .Values.ingressExterno.tls | indent 4 }}
{{- end -}}
{{- end }}
